import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'
import { markdownToHtml } from '@/lib/markdown'

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'codraft-export'
  )
}

function formatDate(d: Date): string {
  return d.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const session = await auth()
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const member = await prisma.roomMember.findUnique({
    where: { roomId_userId: { roomId: params.id, userId: session.user.id } },
  })
  if (!member) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 403 })
  }

  const format = req.nextUrl.searchParams.get('format') ?? 'markdown'
  if (format !== 'markdown' && format !== 'pdf') {
    return NextResponse.json({ error: 'format must be markdown or pdf' }, { status: 400 })
  }

  const room = await prisma.room.findUnique({
    where: { id: params.id },
    include: {
      sections: { orderBy: { order: 'asc' } },
    },
  })
  if (!room) {
    return NextResponse.json({ error: 'Room not found' }, { status: 404 })
  }

  const now = new Date()
  const dateStr = formatDate(now)

  if (format === 'markdown') {
    const body = [
      `# ${room.name}`,
      `> Generated by codraft · ${dateStr}`,
      '',
      '---',
      '',
      ...room.sections.flatMap((s) => [
        `## ${s.name}`,
        s.content?.trim() ? s.content : '_This section is empty._',
        '',
        '---',
        '',
      ]),
    ].join('\n')

    return new NextResponse(body, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${slugify(room.name)}.md"`,
      },
    })
  }

  // PDF path: printable HTML page — user uses browser Print → Save as PDF.
  const sectionHtml = room.sections
    .map((s) => {
      const content = s.content?.trim()
        ? `<div>${markdownToHtml(s.content)}</div>`
        : '<p class="empty">Empty section</p>'
      return `<h2>${escapeHtml(s.name)}</h2>${content}<hr/>`
    })
    .join('\n')

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(room.name)}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111; }
    h1 { font-size: 2rem; border-bottom: 2px solid #111; padding-bottom: 8px; }
    h2 { font-size: 1.3rem; margin-top: 2rem; color: #444; }
    .meta { color: #888; font-size: 0.9rem; margin-bottom: 2rem; }
    .empty { color: #aaa; font-style: italic; }
    hr { border: none; border-top: 1px solid #ddd; margin: 1.5rem 0; }
    .toolbar { display: flex; gap: 8px; margin-bottom: 24px; }
    .toolbar button { padding: 8px 14px; font-size: 14px; cursor: pointer; }
    @media print {
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="no-print toolbar">
    <button onclick="window.print()">🖨️ Print / Save as PDF</button>
    <button onclick="window.close()">Close</button>
  </div>
  <h1>${escapeHtml(room.name)}</h1>
  <p class="meta">Generated by codraft · ${escapeHtml(dateStr)}</p>
  ${sectionHtml}
</body>
</html>`

  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  })
}
